"""prompts the AI can use to generate shitposts"""
prompts = [
  "Anon, you",
  "Attack on Titan",
  "Capitalism can not",
  "Capitalism can",
  "Capitalism is not",
  "Capitalism is",
  "Capitalism was not",
  "Capitalism was",
  "Capitalism will not",
  "Capitalism will",
  "Capitalism",
  "Communism can not",
  "Communism can",
  "Communism is not",
  "Communism is",
  "Communism was not",
  "Communism was",
  "Communism will not",
  "Communism will",
  "Communism",
  "Feminism can not",
  "Feminism can",
  "Feminism is not",
  "Feminism is",
  "Feminism was not",
  "Feminism was",
  "Feminism will not",
  "Feminism will",
  "Feminism",
  "Healthcare can not",
  "Healthcare can",
  "Healthcare is not",
  "Healthcare is",
  "Healthcare was not",
  "Healthcare was",
  "Healthcare will not",
  "Healthcare will",
  "Healthcare",
  "Hitler",
  "I am not",
  "I am",
  "I believe",
  "I don't believe",
  "I don't feel",
  "I don't have",
  "I don't like",
  "I don't need",
  "I don't think",
  "I don't want",
  "I feel",
  "I have never been able to do that because of",
  "I have never been able to do that because",
  "I have never been able to do that",
  "I have never been able to do",
  "I have never been able to",
  "I have never been",
  "I have never",
  "I have",
  "I like",
  "I need",
  "I think",
  "I want",
  "I was",
  "I wasn't",
  "If we do not stop",
  "Left",
  "Right",
  "Sword Art Online",
  "To save the animals",
  "To save the earth",
  "To save the forests",
  "To save the humans",
  "To save the oceans",
  "To save the planet",
  "To save the sea",
  "To save the trees",
  "To save the world",
  "To solve world hunger",
  "Unemployment can not",
  "Unemployment can",
  "Unemployment is not",
  "Unemployment is",
  "Unemployment was not",
  "Unemployment was",
  "Unemployment will not",
  "Unemployment will",
  "Unemployment",
  "We have to do",
  "We have to eradicate the",
  "We have to eradicate",
  "We have to",
  "You",
  "Your mom",
  "Your Waifu is",
  ">",
  "be me",
  "be you",
  "Christianity",
  "Christianity can not",
  "Christianity can",
  "Christianity is not",
  "Christianity is",
  "Christianity was not",
  "Christianity was",
  "Christianity will not",
  "Christianity will",
  "Islam",
  "Islam can not",
  "Islam can",
  "Islam is not",
  "Islam is",
  "Islam was not",
  "Islam was",
  "Islam will not",
  "Islam will",
  "Religion",
  "Religion can not",
  "Religion can",
  "Religion is not",
  "Religion is",
  "Religion was not",
  "Religion was",
  "Religion will not",
  "Religion will",
  "Weebs",
  "Weebs can not",
  "Weebs can",
  "Weebs are not",
  "Weebs are",
  "Weebs were not",
  "Weebs were",
  "Weebs will not",
  "Weebs will",
]
