"""prompts the AI can use to generate shitposts"""
prompts = {
    "noun_sg":{
        "prompts":[
            "/a/",
            "/b/",
            "/pol",
            "/r9k/",
            "/s4s/",
            "4chan",
            "#Anime",
            "Attack on Titan",
            "#Bullying",
            "#Capitalism",
            "#Christianity",
            "#Communism",
            "Copium"
            "#Cyber-Bullying",
            "#Feminism",
            "#Healthcare",
            "Hitler",
            "#Islam",
            "#LGBT",
            "Mankind",
            "#Racism",
            "#Religion",
            "Stalin",
            "Sword Art Online",
            "#Unemployment",
            "Your mom",
            "Your Waifu",
        ],
        "continuations": [
            "",
            "is", "is not",
            "was", "was not",
            "can", "cannot",
            "will", "will not",
            "may", "may not",
            "might", "might not",
            "must", "must not",
        ],
    },
    "noun_pl":{
        "prompts":[
            "Children",
            "Jews",
            "Lefties",
            "#Men",
            "Wagies",
            "#Weebs",
            "#Women",
        ],
        "continuations":[
            "",
            "are", "are not",
            "were", "were not",
            "can", "cannot",
            "will", "will not",
            "may", "may not",
            "might", "might not",
            "must", "must not",
            "feel",
            "like", "don't like",
            "need", "don't need",
            "want", "don't want",
            "think", "don't think",
            "believe", "don't believe",
            "love", "hate"
        ],
    },
    "self":{
        "prompts": [
            "I"
        ],
        "continuations": [
            "",
            "am", "am not",
            "was", "was not",
            "can", "cannot",
            "will", "will not",
            "may", "may not",
            "might", "might not",
            "must", "must not",
            "feel",
            "like", "don't like",
            "need", "don't need",
            "want", "don't want",
            "think", "don't think",
            "believe", "don't believe",
            "love", "hate"
        ],
    },

    "you":{
        "prompts":[
            "Anon, you",
            "We",
            "You",
        ],
        "continuations":[
            "",
            "are", "are not",
            "were", "were not",
            "can", "cannot",
            "will", "will not,",
            "should", "should not",
            "may","may not",
            "might", "might not",
            "must", "must not",
        ],
    },

    "misc": {
        "prompts":[
            ">",
            ">be me",
            ">be you",
            ">be"
            "fuck you",
            "fucking",
            "If we do not stop",
            "Left",
            "Right",
            "To save the animals",
            "To save the earth",
            "To save the planet",
            "To save the world",
            "To solve world hunger",
            "We have to eradicate",
            "We have to",
        ],
        "continuations":[
             "",
        ],
    },
}
